[package]
name = "edrus"
version = "0.1.0"
authors = ["Leonardo Hahn <leonnardo.hahn@gmail.com>"]
edition = "2018"

[lib]
name = "edrus"
path = "src/lib.rs"

[dependencies]
memchr = "2.3.3"
flame = "0.2.2"
flamer = "0.3"

[profile.release]
debug = true